config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/addtable', to: 'tables#save', as: 'create_table'
  get '/show', to: 'tables#show', as: 'show_result'
  # Defines the root path route ("/")
  root  'tables#index'
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/table.rb
class Table < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

    def index

    end
    def save
        file = params[:table]
        fileInfo = Roo::Spreadsheet.open(file.path)
        header = fileInfo.row(1)
        (2..fileInfo.last_row).each do |i|
        row = Hash[[header, fileInfo.row(i)].transpose]
        Table.create!(cliente: row["Cliente"], descripcion: row["Descripción del Producto"], precio: row["Precio por pieza"], cantidad: row["Numero de piezas"], direccion_vendedor: row["Diección del vendedor"], vendedor: row["Nombre del Vendedor"])
        end
        redirect_to action: "show"
    end
    def show
        @total = 0
        @data = Table.all
        @data.each do |sale|
            @total+= sale.precio*sale.cantidad
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba Grupo Orve</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary bg-black mb-5" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Prueba Técnica</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Inicio</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
   <div class = "container">
     <%= yield %>
   </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tables/index.html.erb
<div  class="row mb-3">
    <div class="col text-center">
        <h1>Nueva tabla</h1>
    </div>
</div>
<div class="row">
    <div class="col col-sm-8 offset-sm-2">
        <%= form_tag create_table_path, multipart: true do %>
        <div class="mb-3">
            <%= file_field_tag :table, :class=>'form-control' %>
        </div>
        <%= submit_tag "Enviar", :class =>'btn btn-primary' %>
<% end %>
    </div>
</div>       

app/views/tables/show.html.erb
<div  class="row mb-3">
  <div class="col text-center">
    <h1>Resultado de la exportación</h1>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <table class = "table table-striped table-hover">
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Descripción del Producto</th>
          <th>Precio</th>
          <th>Cantidad</th>
          <th>Dirección del Vendedor</th>
          <th>Vendedor</th>
        </tr>
      </thead>
      <tbody>
      <% @data.each do |sale| %>
        <tr>
          <td><%=sale.cliente %></td>
          <td><%=sale.descripcion %></td>
          <td><%=sale.precio %></td>
          <td><%=sale.cantidad %></td>
          <td><%=sale.direccion_vendedor %></td>
          <td><%=sale.vendedor %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-12">
    <div class="alert alert-primary" role="alert">
      El total de las ventas es de: <%=number_to_currency(@total) %>
    </div>
  </div>
</div>